// Code generated by protoc-gen-go. DO NOT EDIT.
// source: testmessage.proto

/*
Package testdata is a generated protocol buffer package.

It is generated from these files:
	testmessage.proto

It has these top-level messages:
	TestMessage
*/
package testdata

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TestMessage struct {
	RegInt32   int32          `protobuf:"varint,1,opt,name=RegInt32" json:"RegInt32,omitempty"`
	RegInt64   int64          `protobuf:"varint,2,opt,name=RegInt64" json:"RegInt64,omitempty"`
	RegUint32  uint32         `protobuf:"varint,3,opt,name=RegUint32" json:"RegUint32,omitempty"`
	RegUint64  uint64         `protobuf:"varint,4,opt,name=RegUint64" json:"RegUint64,omitempty"`
	RegFloat32 float32        `protobuf:"fixed32,5,opt,name=RegFloat32" json:"RegFloat32,omitempty"`
	RegFloat64 float64        `protobuf:"fixed64,6,opt,name=RegFloat64" json:"RegFloat64,omitempty"`
	RegBool    bool           `protobuf:"varint,7,opt,name=RegBool" json:"RegBool,omitempty"`
	RegString  string         `protobuf:"bytes,8,opt,name=RegString" json:"RegString,omitempty"`
	RegBytes   []byte         `protobuf:"bytes,9,opt,name=RegBytes,proto3" json:"RegBytes,omitempty"`
	RegEntity  *TestMessage   `protobuf:"bytes,10,opt,name=RegEntity" json:"RegEntity,omitempty"`
	ArrInt32   []int32        `protobuf:"varint,11,rep,packed,name=ArrInt32" json:"ArrInt32,omitempty"`
	ArrInt64   []int64        `protobuf:"varint,12,rep,packed,name=ArrInt64" json:"ArrInt64,omitempty"`
	ArrUint32  []uint32       `protobuf:"varint,13,rep,packed,name=ArrUint32" json:"ArrUint32,omitempty"`
	ArrUint64  []uint64       `protobuf:"varint,14,rep,packed,name=ArrUint64" json:"ArrUint64,omitempty"`
	ArrFloat32 []float32      `protobuf:"fixed32,15,rep,packed,name=ArrFloat32" json:"ArrFloat32,omitempty"`
	ArrFloat64 []float64      `protobuf:"fixed64,16,rep,packed,name=ArrFloat64" json:"ArrFloat64,omitempty"`
	ArrBool    []bool         `protobuf:"varint,17,rep,packed,name=ArrBool" json:"ArrBool,omitempty"`
	ArrString  []string       `protobuf:"bytes,18,rep,name=ArrString" json:"ArrString,omitempty"`
	ArrBytes   [][]byte       `protobuf:"bytes,19,rep,name=ArrBytes,proto3" json:"ArrBytes,omitempty"`
	ArrEntity  []*TestMessage `protobuf:"bytes,20,rep,name=ArrEntity" json:"ArrEntity,omitempty"`
}

func (m *TestMessage) Reset()                    { *m = TestMessage{} }
func (m *TestMessage) String() string            { return proto.CompactTextString(m) }
func (*TestMessage) ProtoMessage()               {}
func (*TestMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TestMessage) GetRegInt32() int32 {
	if m != nil {
		return m.RegInt32
	}
	return 0
}

func (m *TestMessage) GetRegInt64() int64 {
	if m != nil {
		return m.RegInt64
	}
	return 0
}

func (m *TestMessage) GetRegUint32() uint32 {
	if m != nil {
		return m.RegUint32
	}
	return 0
}

func (m *TestMessage) GetRegUint64() uint64 {
	if m != nil {
		return m.RegUint64
	}
	return 0
}

func (m *TestMessage) GetRegFloat32() float32 {
	if m != nil {
		return m.RegFloat32
	}
	return 0
}

func (m *TestMessage) GetRegFloat64() float64 {
	if m != nil {
		return m.RegFloat64
	}
	return 0
}

func (m *TestMessage) GetRegBool() bool {
	if m != nil {
		return m.RegBool
	}
	return false
}

func (m *TestMessage) GetRegString() string {
	if m != nil {
		return m.RegString
	}
	return ""
}

func (m *TestMessage) GetRegBytes() []byte {
	if m != nil {
		return m.RegBytes
	}
	return nil
}

func (m *TestMessage) GetRegEntity() *TestMessage {
	if m != nil {
		return m.RegEntity
	}
	return nil
}

func (m *TestMessage) GetArrInt32() []int32 {
	if m != nil {
		return m.ArrInt32
	}
	return nil
}

func (m *TestMessage) GetArrInt64() []int64 {
	if m != nil {
		return m.ArrInt64
	}
	return nil
}

func (m *TestMessage) GetArrUint32() []uint32 {
	if m != nil {
		return m.ArrUint32
	}
	return nil
}

func (m *TestMessage) GetArrUint64() []uint64 {
	if m != nil {
		return m.ArrUint64
	}
	return nil
}

func (m *TestMessage) GetArrFloat32() []float32 {
	if m != nil {
		return m.ArrFloat32
	}
	return nil
}

func (m *TestMessage) GetArrFloat64() []float64 {
	if m != nil {
		return m.ArrFloat64
	}
	return nil
}

func (m *TestMessage) GetArrBool() []bool {
	if m != nil {
		return m.ArrBool
	}
	return nil
}

func (m *TestMessage) GetArrString() []string {
	if m != nil {
		return m.ArrString
	}
	return nil
}

func (m *TestMessage) GetArrBytes() [][]byte {
	if m != nil {
		return m.ArrBytes
	}
	return nil
}

func (m *TestMessage) GetArrEntity() []*TestMessage {
	if m != nil {
		return m.ArrEntity
	}
	return nil
}

func init() {
	proto.RegisterType((*TestMessage)(nil), "testdata.TestMessage")
}

func init() { proto.RegisterFile("testmessage.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0xc6, 0xe5, 0xba, 0x7f, 0x52, 0xb7, 0x05, 0x6a, 0x40, 0xb2, 0x10, 0x42, 0x27, 0x26, 0x4f,
	0x1d, 0xda, 0x28, 0x7b, 0x2a, 0x81, 0xc4, 0xc0, 0x72, 0xc0, 0x03, 0x04, 0x61, 0x45, 0x95, 0x4a,
	0x83, 0x1c, 0x2f, 0x7d, 0x02, 0x5e, 0x1b, 0x5d, 0xe2, 0xd8, 0x9e, 0x18, 0xbf, 0xdf, 0xe7, 0x8b,
	0x73, 0x3f, 0x59, 0xac, 0x9d, 0x69, 0xdd, 0xb7, 0x69, 0xdb, 0xaa, 0x36, 0x9b, 0x1f, 0xdb, 0xb8,
	0x46, 0x66, 0x84, 0xbe, 0x2a, 0x57, 0x3d, 0xfe, 0x4e, 0xc4, 0xe2, 0xdd, 0xb4, 0xee, 0xb5, 0xef,
	0xe5, 0x9d, 0xc8, 0xd0, 0xd4, 0x2f, 0x27, 0xb7, 0xdb, 0x2a, 0x06, 0x4c, 0x4f, 0x30, 0xe4, 0xd8,
	0x15, 0xb9, 0x1a, 0x01, 0xd3, 0x1c, 0x43, 0x96, 0xf7, 0x62, 0x8e, 0xa6, 0xfe, 0x38, 0x74, 0x83,
	0x1c, 0x98, 0x5e, 0x61, 0x04, 0x49, 0x5b, 0xe4, 0x6a, 0x0c, 0x4c, 0x8f, 0x31, 0x02, 0xf9, 0x20,
	0x04, 0x9a, 0xfa, 0xf9, 0xd8, 0x54, 0x34, 0x3c, 0x01, 0xa6, 0x47, 0x98, 0x90, 0xb4, 0x2f, 0x72,
	0x35, 0x05, 0xa6, 0x19, 0x26, 0x44, 0x2a, 0x31, 0x43, 0x53, 0xef, 0x9b, 0xe6, 0xa8, 0x66, 0xc0,
	0x74, 0x86, 0x43, 0xf4, 0xf7, 0xbe, 0x39, 0x7b, 0x38, 0xd5, 0x2a, 0x03, 0xa6, 0xe7, 0x18, 0x81,
	0xdf, 0x67, 0x7f, 0x76, 0xa6, 0x55, 0x73, 0x60, 0x7a, 0x89, 0x21, 0xcb, 0x5d, 0x37, 0xf9, 0x74,
	0x72, 0x07, 0x77, 0x56, 0x02, 0x98, 0x5e, 0x6c, 0x6f, 0x37, 0x83, 0xb5, 0x4d, 0x62, 0x0c, 0xe3,
	0x39, 0xfa, 0x60, 0x69, 0x6d, 0x2f, 0x6f, 0x01, 0x9c, 0xe4, 0x0d, 0x39, 0x76, 0x45, 0xae, 0x96,
	0xc0, 0x49, 0xde, 0x90, 0xe9, 0x37, 0x4b, 0x6b, 0xbd, 0xbc, 0x15, 0x70, 0x92, 0x17, 0x40, 0xd2,
	0x16, 0xb9, 0xba, 0x00, 0x4e, 0xf2, 0x02, 0x20, 0x39, 0xa5, 0xb5, 0x83, 0xbc, 0x4b, 0xe0, 0x24,
	0x2f, 0x92, 0xb4, 0x2f, 0x72, 0x75, 0x05, 0x9c, 0xe4, 0x45, 0x42, 0xf2, 0x4a, 0x6b, 0x3b, 0x79,
	0x6b, 0xe0, 0x24, 0xcf, 0x47, 0x7f, 0xaf, 0x97, 0x27, 0x81, 0x93, 0xbc, 0x00, 0xfc, 0x3e, 0xbd,
	0xbc, 0x6b, 0xe0, 0x24, 0x6f, 0xc8, 0x24, 0xaf, 0xb4, 0xd6, 0xcb, 0xbb, 0x01, 0xfe, 0x8f, 0xbc,
	0x70, 0xee, 0x73, 0xda, 0x3d, 0xcd, 0xdd, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x85, 0x97, 0x57,
	0x10, 0xaf, 0x02, 0x00, 0x00,
}
